// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import DashboardOutlined from '/Users/zhaolong/前端/vibe-coding-project/taste-food/admin/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import ShopOutlined from '/Users/zhaolong/前端/vibe-coding-project/taste-food/admin/node_modules/@ant-design/icons/es/icons/ShopOutlined';
import CoffeeOutlined from '/Users/zhaolong/前端/vibe-coding-project/taste-food/admin/node_modules/@ant-design/icons/es/icons/CoffeeOutlined';
import OrderedListOutlined from '/Users/zhaolong/前端/vibe-coding-project/taste-food/admin/node_modules/@ant-design/icons/es/icons/OrderedListOutlined';
import TeamOutlined from '/Users/zhaolong/前端/vibe-coding-project/taste-food/admin/node_modules/@ant-design/icons/es/icons/TeamOutlined';
import GiftOutlined from '/Users/zhaolong/前端/vibe-coding-project/taste-food/admin/node_modules/@ant-design/icons/es/icons/GiftOutlined';
import AuditOutlined from '/Users/zhaolong/前端/vibe-coding-project/taste-food/admin/node_modules/@ant-design/icons/es/icons/AuditOutlined';
export default { DashboardOutlined, ShopOutlined, CoffeeOutlined, OrderedListOutlined, TeamOutlined, GiftOutlined, AuditOutlined };
