// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_2 from '/Users/zhaolong/前端/vibe-coding-project/taste-food/admin/src/.umi-production/plugin-initialState/@@initialState';
import model_1 from '/Users/zhaolong/前端/vibe-coding-project/taste-food/admin/src/models/shopContext';

export const models = {
model_2: { namespace: '@@initialState', model: model_2 },
model_1: { namespace: 'shopContext', model: model_1 },
} as const
