// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import UserOutlined from '/Users/zhaolong/前端/vibe-coding-project/taste-food/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/UserOutlined';
import DashboardOutlined from '/Users/zhaolong/前端/vibe-coding-project/taste-food/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import SafetyCertificateOutlined from '/Users/zhaolong/前端/vibe-coding-project/taste-food/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/SafetyCertificateOutlined';
import AuditOutlined from '/Users/zhaolong/前端/vibe-coding-project/taste-food/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/AuditOutlined';
import OrderedListOutlined from '/Users/zhaolong/前端/vibe-coding-project/taste-food/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/OrderedListOutlined';
import CoffeeOutlined from '/Users/zhaolong/前端/vibe-coding-project/taste-food/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/CoffeeOutlined';
import GiftOutlined from '/Users/zhaolong/前端/vibe-coding-project/taste-food/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/GiftOutlined';
import TeamOutlined from '/Users/zhaolong/前端/vibe-coding-project/taste-food/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/TeamOutlined';
import ShopOutlined from '/Users/zhaolong/前端/vibe-coding-project/taste-food/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ShopOutlined';
import FileExcelOutlined from '/Users/zhaolong/前端/vibe-coding-project/taste-food/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/FileExcelOutlined';
import SoundOutlined from '/Users/zhaolong/前端/vibe-coding-project/taste-food/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/SoundOutlined';
export default { UserOutlined, DashboardOutlined, SafetyCertificateOutlined, AuditOutlined, OrderedListOutlined, CoffeeOutlined, GiftOutlined, TeamOutlined, ShopOutlined, FileExcelOutlined, SoundOutlined };
